# Generated by Django 5.2.4 on 2025-08-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_funcionario_cargo_secretaria'),
        ('registry', '0002_secretaria_nome_secretaria_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
    ]
