# Generated by Django 5.2.4 on 2025-08-10 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0003_delete_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=150)),
                ('secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registry.secretaria')),
            ],
        ),
    ]
