# Generated by Django 5.2.4 on 2025-08-07 14:10

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(default='2000-02-02')),
                ('numero', models.CharField(max_length=11)),
                ('cpf', models.CharField(max_length=11)),
                ('genero', models.CharField(max_length=20)),
                ('estado_civil', models.CharField(max_length=20)),
                ('cargo', models.CharField(choices=[('F', 'Funcionário'), ('S', 'Secretário'), ('G', 'Gestor')], default='F', max_length=20)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
