# Generated by Django 5.2.4 on 2025-08-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('F', 'Funcionário'), ('S', 'Secretário'), ('G', 'Gestor')], default='F', max_length=20),
        ),
    ]
