# Generated by Django 5.2.4 on 2025-08-08 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='data_nascimento',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='estado_civil',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='genero',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='numero',
        ),
    ]
