# Generated by Django 5.2.4 on 2025-08-09 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_funcionario_cpf_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='nome_completo',
        ),
    ]
