# Generated by Django 5.2.4 on 2025-08-10 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_funcionario_cargo'),
        ('registry', '0002_secretaria_nome_secretaria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo_secretaria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='registry.cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='secretaria_servico',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarias', to='registry.secretaria'),
        ),
    ]
