# Generated by Django 5.2.4 on 2025-08-10 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_funcionario_cargo_secretaria_and_more'),
    ]

    operations = [
        
    ]
