# Generated by Django 5.2.4 on 2025-08-11 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_funcionario_cargo_alter_funcionario_cargo_secretaria_and_more'),
        ('accounts', '0002_remove_funcionario_cpf_and_more'),
        ('accounts', '0002_rename_funcao_funcionario_cargo'),
        ('accounts', '0003_alter_funcionario_cargo_secretaria_and_more'),
        # ('accounts', '0004_remove_funcionario_cargo_secretaria'),
    ]

    operations = [
    ]
