# Generated by Django 5.2.4 on 2025-08-11 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_funcionario_cargo_secretaria'),
        ('accounts', '0005_merge_20250811_1203'),
    ]

    operations = [
    ]
