# Generated by Django 5.2.4 on 2025-08-11 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_merge_20250811_1204'),
        ('registry', '0004_cargo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='nome_completo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo_secretaria',
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('F', 'Funcionário'), ('S', 'Secretario'), ('G', 'Gestor')], default='F', max_length=20),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='secretaria_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarias', to='registry.secretaria'),
        ),
    ]
