# Generated by Django 5.2.4 on 2025-08-11 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_nome_funcionario_nome_completo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='secretaria_servico',
        ),
    ]
