# Generated by Django 5.2.4 on 2025-08-11 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_funcionario_secretaria_servico'),
        ('registry', '0004_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='secretaria_trabalho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='secretarias', to='registry.secretaria'),
        ),
    ]
