# Generated by Django 5.2.4 on 2025-08-11 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_funcionario_secretaria_trabalho'),
        ('registry', '0004_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cargo_trabalho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cargos', to='registry.cargo'),
        ),
    ]
