# Generated by Django 5.2.4 on 2025-08-14 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_funcionario_cargo_trabalho'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo_trabalho',
        ),
    ]
