# Generated by Django 5.2.4 on 2025-08-14 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_funcionario_cargo_trabalho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('F', 'Funcionário'), ('S', 'Secretario')], default='F', max_length=20),
        ),
    ]
