# Generated by Django 5.2.4 on 2025-08-14 18:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_expiracao',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
