# Generated by Django 5.2.4 on 2025-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_funcionario_data_expiracao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('S', 'Secretario'), ('G', 'Gestor')], default='S', max_length=20),
        ),
    ]
