# Generated by Django 5.2.4 on 2025-08-31 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(choices=[('S', 'Secretario'), ('P', 'Prefeito'), ('D', 'Diretor'), ('T', 'Tecnico'), ('C', 'Coordenador')], default='S', max_length=20),
        ),
    ]
