# Generated by Django 5.2.4 on 2025-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_alter_funcionario_cargo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='data_nascimento',
            field=models.DateField(blank=True, default='2000-02-02', null=True),
        ),
        migrations.AddField(
            model_name='funcionario',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('PF', 'Prefiro não dizer')], default='PF', max_length=20),
        ),
    ]
