# Generated by Django 5.2.4 on 2025-09-01 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_funcionario_data_nascimento_funcionario_genero'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pontuacao_tarefas',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
