# Generated by Django 5.2.4 on 2025-08-11 15:24

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_remove_funcionario_secretaria_servico'),
        ('registry', '0004_cargo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('missao_tarefa', models.CharField(max_length=150)),
                ('descricao_tarefa', models.TextField()),
                ('prazo_tarefa', models.DateTimeField(default=django.utils.timezone.now)),
                ('status_tarefa', models.CharField(choices=[('AF', 'A Fazer'), ('A', 'Andamento'), ('C', 'Concluída'), ('E', 'Expirada')], default='AF', max_length=20)),
                ('anexo_tarefa', models.FileField(upload_to='documentos/')),
                ('prioridade_tarefa', models.CharField(choices=[('U', 'Urgente'), ('A', 'Alta'), ('M', 'Médio'), ('B', 'Baixa')], default='B', max_length=20)),
                # ('id_criador', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_criadas', to='accounts.funcionario', verbose_name='Criador')),
                ('id_secretaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='registry.secretaria')),
            ],
        ),
    ]
