# Generated by Django 5.2.4 on 2025-08-11 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_funcionario_secretaria_servico'),
        ('tasks', '0001_initial'),
    ]

    operations = [

    ]
