# Generated by Django 5.2.4 on 2025-08-11 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_tarefa_id_criador'),
    ]

    operations = [

    ]
