# Generated by Django 5.2.4 on 2025-08-11 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_funcionario_cargo_trabalho'),
        ('tasks', '0003_remove_tarefa_id_criador'),
    ]

    operations = [

    ]
