# Generated by Django 5.2.4 on 2025-08-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_funcionario_cargo_trabalho'),
        ('registry', '0004_cargo'),
        ('tasks', '0004_tarefa_id_criador'),
    ]

    operations = [

        migrations.AddField(
            model_name='tarefa',
            name='tarefa_usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taredas_usuario', to='accounts.funcionario'),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='id_secretaria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='registry.secretaria'),
        ),
    ]
