# Generated by Django 5.2.4 on 2025-08-11 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_remove_tarefa_id_criador_tarefa_tarefa_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='anexo_tarefa',
            field=models.FileField(blank=True, null=True, upload_to='documentos/'),
        ),
    ]
