# Generated by Django 5.2.4 on 2025-08-11 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_cargo'),
        ('tasks', '0006_alter_tarefa_anexo_tarefa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarefa',
            name='tarefa_usuario',
        ),
        migrations.AddField(
            model_name='tarefa',
            name='tarefa_cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taredas_cargo', to='registry.cargo'),
        ),
    ]
