# Generated by Django 5.2.4 on 2025-08-11 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registry', '0004_cargo'),
        ('tasks', '0007_remove_tarefa_tarefa_usuario_tarefa_tarefa_cargo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='id_secretaria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas', to='registry.secretaria'),
        ),
    ]
