# Generated by Django 5.2.4 on 2025-08-12 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_funcionario_cargo_trabalho'),
        ('tasks', '0008_alter_tarefa_id_secretaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='id_criador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tarefas_criado', to='accounts.funcionario'),
        ),
    ]
