# Generated by Django 5.2.4 on 2025-08-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_tarefa_id_criador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prioridade_tarefa',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Médio'), ('A', 'Alta'), ('U', 'Urgente')], default='B', max_length=20),
        ),
    ]
