# Generated by Django 5.2.4 on 2025-08-12 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_funcionario_cargo_trabalho'),
        ('tasks', '0010_alter_tarefa_prioridade_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='id_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_responsavel', to='accounts.funcionario'),
        ),
    ]
