# Generated by Django 5.2.4 on 2025-08-13 13:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_tarefa_id_responsavel'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tarefa',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='is_active',
            field=models.BooleanField(default=True, editable=False),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
