# Generated by Django 5.2.4 on 2025-08-14 00:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_tarefa_created_at_tarefa_deleted_at_tarefa_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='prazo_tarefa',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
