# Generated by Django 5.2.4 on 2025-08-14 13:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_funcionario_cargo'),
        ('tasks', '0013_alter_tarefa_prazo_tarefa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('is_active', models.BooleanField(default=True, editable=False)),
                ('motivo_agenda', models.CharField(max_length=200)),
                ('local_agenda', models.CharField(blank=True, max_length=150, null=True)),
                ('data_agenda', models.DateField(default=django.utils.timezone.now)),
                ('hora_agenda', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('status_agenda', models.CharField(blank=True, choices=[('R', 'Realizada'), ('AF', 'A Fazer')], default='AF', max_length=20, null=True)),
                ('id_criador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendas_criador', to='accounts.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
