# Generated by Django 5.2.4 on 2025-08-14 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_agenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='hora_tarefa',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
