# Generated by Django 5.2.4 on 2025-08-18 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_tarefa_hora_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='descricao_tarefa',
            field=models.TextField(blank=True, null=True),
        ),
    ]
