# Generated by Django 5.2.4 on 2025-08-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_alter_tarefa_descricao_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='descricao_agenda',
            field=models.TextField(blank=True, null=True),
        ),
    ]
