# Generated by Django 5.2.4 on 2025-08-18 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_agenda_descricao_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_agenda',
            field=models.CharField(blank=True, choices=[('R', 'Realizada'), ('A', 'A Fazer')], default='A', max_length=20, null=True),
        ),
    ]
