# Generated by Django 5.2.4 on 2025-08-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_agenda_status_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='status_agenda',
            field=models.CharField(blank=True, choices=[('A', 'Agendado'), ('AD', 'Adiado'), ('RA', 'Reagendado'), ('E', 'Encerrado'), ('C', 'Cancelado'), ('R', 'Realizado')], default='A', max_length=20, null=True),
        ),
    ]
