# Generated by Django 5.2.4 on 2025-08-31 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_agenda_status_agenda'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_agenda',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora_tarefa',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
