# Generated by Django 5.2.4 on 2025-08-31 22:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0020_alter_agenda_hora_agenda_alter_tarefa_hora_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='hora_agenda',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='tarefa',
            name='hora_tarefa',
            field=models.TimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
