# Generated by Django 5.2.4 on 2025-09-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_alter_agenda_hora_agenda_alter_tarefa_hora_tarefa'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='pontuacao_tarefa',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
