# Generated by Django 5.2.4 on 2025-09-01 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0022_tarefa_pontuacao_tarefa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefa',
            name='pontuacao_tarefa',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
